### PR TITLE
fix: downscope credentials used for IAM AuthN login

### LINKED ISSUE #996: Downscope OAuth2 token included in ephemeral certificate
The token included in the ephemeral cert should have just a `https://www.googleapis.com/auth/sqlservice.login` scope attached to it.

### PR DESCRIPTION
**Pull request by shubha-rajan**
## Relevant issues:

- Fixes #996

### CODE REVIEW

**Review by enocom — APPROVED** [review]

**Comment by shubha-rajan** [comment]
Looks like the Code Coverage check wants me to add a test

**Comment by enocom** [comment]
One option for writing a test: extract the logic here into a method that accepts a Credentials object. Then you could test what happens when that token does not supported GoogleCredentials, what happens when the credentials are scoped, etc.

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java [hunk 1]
```diff
@@ -526,7 +528,17 @@ private Certificate fetchEphemeralCertificate(KeyPair keyPair) {
     if (enableIamAuth) {
       try {
         credentials.get().refresh();
```
Comment (kurtisvg) [inline core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:530]: Can we refresh after we downscope?

**Review by kurtisvg — CHANGES_REQUESTED** [review]

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java (hunk 1 above)
Comment (shubha-rajan) [reply core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java]: Unfortunately no,  we get a nullpointer if we do that.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+  private GoogleCredentials scopedCredentials;
+
+  @Mock
+  private OAuth2Credentials oAuth2Credentials;
+
+  @Before
+  public void setup() throws IOException {
+    MockitoAnnotations.openMocks(this);
+    when(googleCredentials.createScoped(
+        "https://www.googleapis.com/auth/sqlservice.login")).thenReturn(scopedCredentials);
```
Comment (kurtisvg) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java:49]: Are we sure that this is testing the right thing? Since the mock isn't set, is there a possibility this is just testing that they are null?

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java [hunk 3]
```diff
@@ -525,8 +527,11 @@ private Certificate fetchEphemeralCertificate(KeyPair keyPair) {
 
     if (enableIamAuth) {
       try {
-        credentials.get().refresh();
-        String token = credentials.get().getAccessToken().getTokenValue();
+        OAuth2Credentials creds = credentials.get();
+        creds.refresh();
+        GoogleCredentials downscoped = getDownscopedCredentials(creds);
+        downscoped.refresh();
```
Comment (kurtisvg) [inline core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:533]: I'd like to better understand why we need to refresh twice here?

**Review by kurtisvg — CHANGES_REQUESTED** [review]
