### PR TITLE
Consolidate "connect" logic from individual factories into core SocketFactory.

### LINKED ISSUE #113: 1.0.11 is not backwards compatible to 1.0.10 (postgresql)
in 1.0.10, you could include the `socketFactoryArg` parameter in your jdbc url in order to pass the cloudSqlInstance name. In 1.0.11, doing this leads to the value not being found by the SocketFactory constructor, failing the call to `checkArgument` in line 53 of `com.google.cloud.sql.postgres.SocketFactory`.

IMHO, API breakage should not happen on micro bumps. There also is no explicit reference to this in the release notes AFAICS.

### PR DESCRIPTION
**Pull request by kurtisvg**
Consolidates the "connect" function logic from being implemented in each Factory into the core Socket Factory. 

Notable changes:
* Renamed core "SslSocketFactory" to "CoreSocketFactory" to better reflect it now returns multiple types of sockets
* Renamed the "create" function to "createSslSocketFactory"
* Implemented a new "create" function containing the ssl/unix socket determination and implemented in each factory 
* As a side effect, cleaned up the way "SocketFactoryArg" deprecation was handled that fixes #113

### CODE REVIEW

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java [hunk 1]
```diff
@@ -77,11 +82,15 @@
  *
  * <p>The API of this class is subject to change without notice.
  */
-public class SslSocketFactory {
-  private static final Logger logger = Logger.getLogger(SslSocketFactory.class.getName());
+public class CoreSocketFactory {
+  public static final String CLOUD_SQL_INSTANCE_PROPERTY = "cloudSqlInstance";
```
Comment (netdpb) [inline core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]: Do these all need to be public?

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java [hunk 2]
```diff
@@ -93,7 +102,7 @@
   private static final int DEFAULT_SERVER_PROXY_PORT = 3307;
   private static final int RSA_KEY_SIZE = 2048;
 
-  private static SslSocketFactory sslSocketFactory;
+  private static CoreSocketFactory sslSocketFactory;
```
Comment (netdpb) [inline core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]: Can you rename the field to be consistent?

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java [hunk 3]
```diff
@@ -126,11 +135,12 @@
   }
 
   /**
-   * Returns the SslSocketFactory singleton, which can be used to create SslSockets to Cloud SQL.
+   * Returns the CoreSocketFactory singleton, which can be used to createSslSocket SslSockets to
+   * Cloud SQL.
    *
-   * @return the SslSocketFactory singleton.
+   * @return the CoreSocketFactory singleton.
```
Comment (netdpb) [inline core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]: You don't need this if it simply repeats what's in the summary.

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java [hunk 4]
```diff
@@ -126,11 +135,12 @@
   }
 
   /**
-   * Returns the SslSocketFactory singleton, which can be used to create SslSockets to Cloud SQL.
+   * Returns the CoreSocketFactory singleton, which can be used to createSslSocket SslSockets to
```
Comment (netdpb) [inline core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]:
```suggestion
   * Returns the {@link CoreSocketFactory} singleton.
```

What it does is documented elsewhere.

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java [hunk 5]
```diff
@@ -152,12 +162,61 @@ public static synchronized SslSocketFactory getInstance() {
...
+          String.format(
+              "Connecting to Cloud SQL instance [%s] via unix socket.", csqlInstanceName));
+      UnixSocketAddress socketAddress =
+          new UnixSocketAddress(new File(String.format(socketPathFormat, csqlInstanceName)));
+      return UnixSocketChannel.open(socketAddress).socket();
+    }
+
+    logger.info(
+        String.format("Connecting to Cloud SQL instance [%s] via SSL socket.", csqlInstanceName));
+    return CoreSocketFactory.getInstance().createSslSocket(csqlInstanceName, ipTypes);
```
Comment (netdpb) [inline core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]:
```suggestion
    return getInstance().createSslSocket(csqlInstanceName, ipTypes);
```

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java [hunk 6]
```diff
@@ -77,11 +82,15 @@
  *
  * <p>The API of this class is subject to change without notice.
  */
-public class SslSocketFactory {
-  private static final Logger logger = Logger.getLogger(SslSocketFactory.class.getName());
+public class CoreSocketFactory {
```
Comment (netdpb) [inline core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]: Can this class be final?

File: core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java [hunk 7]
```diff
@@ -151,17 +151,17 @@ public void setup() throws IOException, GeneralSecurityException {
 
   @Test
   public void create_throwsErrorForInvalidInstanceName() throws IOException {
-    SslSocketFactory sslSocketFactory =
-        new SslSocketFactory(new Clock(), clientKeyPair, credential, adminApi, 3307);
+    CoreSocketFactory sslSocketFactory =
```
Comment (netdpb) [inline core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java]: Rename the variable too?

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java (hunk 1 above)
Comment (kurtisvg) [reply core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]: Yes - the property is used to the Postgres SF to deal with a backwards compatibility issue  cause by a change in the PGdriver API (it carries the arg under a different key forward to the new key).

The two file formats are passed into the connect method (since the Postgres format requires a suffix). I could create an overloaded method for each, but at some point we may want users to be able to specify a different address, so I thought I would just expose the defaults for now.

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java (hunk 2 above)
Comment (kurtisvg) [reply core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]: Done.

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java (hunk 3 above)
Comment (kurtisvg) [reply core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]: Removed.

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java (hunk 6 above)
Comment (kurtisvg) [reply core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]: Done.

File: core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java (hunk 7 above)
Comment (kurtisvg) [reply core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java]: Done.

File: connector-j-5/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java [hunk 8]
```diff
@@ -16,64 +16,30 @@
...
+    return socket;
   }
 
   // Cloud SQL sockets always use TLS and the socket returned by connect above is already TLS-ready.
-  // It is fine
-  // to implement these as no-ops.
+  // It is fine to implement these as no-ops.
   @Override
   public Socket beforeHandshake() {
     return socket;
```
[the remark this answers is not in the document]
Comment (kurtisvg) [reply connector-j-5/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java]: My understanding is that it is connect -> beforeHandshake -> afterHandshake.

It's not 100% clear based on the [documentation](https://github.com/mysql/mysql-connector-j/blob/66459e9d39c8fd09767992bc592acd2053279be6/src/legacy/java/com/mysql/jdbc/SocketFactory.java#L69). However our current implementation actually implements the SSL stuff itself in the CoreSocketFactory.

[the remark this answers is not in the document]
Comment (netdpb) [reply connector-j-5/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java]: So they expect the factory to hold onto its single connection. So weird.

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java (hunk 1 above)
Comment (netdpb) [reply core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]: OK. We can deal with this in followup PRs, but I'm worried about String parameters that are really more constrained.

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java [hunk 9]
```diff
@@ -135,13 +135,10 @@
   }
 
   /**
-   * Returns the CoreSocketFactory singleton, which can be used to createSslSocket SslSockets to
-   * Cloud SQL.
-   *
-   * @return the CoreSocketFactory singleton.
+   * Returns the {@link CoreSocketFactory} singleton.
```
Comment (netdpb) [inline core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]: Make sure to run google-java-format before merging.

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java [hunk 10]
```diff
@@ -226,7 +223,7 @@ private boolean runningOnGaeStandard() {
    * @throws IOException if error occurs during socket creation.
    */
   // TODO(berezv): separate creating socket and performing connection to make it easier to test
-  public Socket createSslSocket(String instanceName, List<String> ipTypes) throws IOException {
+  protected Socket createSslSocket(String instanceName, List<String> ipTypes) throws IOException {
```
Comment (netdpb) [inline core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java]: Why `protected`? It's a final class.
