### PR TITLE
fix: Retry when attempting to get the auth token

### LINKED ISSUE #1127: sql.postgres.JdbcPostgresIamAuthIntegrationTests: pooledConnectionTest failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: cc6b239f964ea899b0ec6210f0bfa85ddb52461a
buildURL: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/3961297087
status: failed
<details><summary>Test output</summary><br><pre>java.lang.NullPointerException: Cannot invoke "com.zaxxer.hikari.HikariDataSource.getConnection()" because "this.connectionPool" is null
	at com.google.cloud.sql.postgres.JdbcPostgresIamAuthIntegrationTests.dropTableIfPresent(JdbcPostgresIamAuthIntegrationTests.java:111)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></details>

### LINKED ISSUE #1288: sql.mariadb.JdbcMariaDBIamAuthIntegrationTests: pooledConnectionTest failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: bf952b5c55a9629d42ab195c7d0cb7a790af7b85
buildURL: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4942709198
status: failed
<details><summary>Test output</summary><br><pre>java.lang.NullPointerException: Cannot invoke "com.zaxxer.hikari.HikariDataSource.getConnection()" because "this.connectionPool" is null
	at com.google.cloud.sql.mariadb.JdbcMariaDBIamAuthIntegrationTests.dropTableIfPresent(JdbcMariaDBIamAuthIntegrationTests.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></details>

### PR DESCRIPTION
**Pull request by hessjcg**
Simplifies the logic when attempting to get the first token for a connection with IAM AuthN enabled. Also, adds logic
to retry the token request 3 times if it initially fails. 

Fixes #1288 
Fixes #1127

### CODE REVIEW

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java [hunk 1]
```diff
@@ -245,23 +244,17 @@ private InstanceData performRefresh() throws InterruptedException, ExecutionExce
...
 
     ListenableFuture<InstanceData> refreshFuture;
-    if (authType == AuthType.IAM) {
-      if (credentials.isPresent()) {
-        GoogleCredentials downscopedCredentials = getDownscopedCredentials(credentials.get());
-        refreshFuture =
-            apiFetcher.getInstanceData(
-                instanceName, downscopedCredentials, AuthType.IAM, executor, keyPair);
-      } else {
-        throw new RuntimeException(
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:255]: We probably still need to throw an exception when no credentials have been provided.

File: core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java [hunk 2]
```diff
@@ -318,6 +319,40 @@ private Certificate fetchEphemeralCertificate(
...
   }
 
+  /**
+   * refreshWithRetry attempts to refresh the credentials 3 times, waiting 3-6 seconds between
+   * attempts.
+   *
+   * @param credentials the credentials to refresh
+   * @throws IOException when the credentials.refresh() has failed 3 times
+   */
+  private void refreshWithRetry(OAuth2Credentials credentials) throws IOException {
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java:329]: Should we be adding a test for this? Something like a CredentialRefresher maybe?

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java (hunk 1 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:255]: I think that case is covered on line 104. There is no way to create a CloudSQLInstance with authType == IAM leaving this.iamAuthnCredentials with an empty value. Optional.of(null) will throw an exception.

File: core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java (hunk 2 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java:329]: Good idea. I'll add one.

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java (hunk 1 above)
Comment (enocom) [reply core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:255]: Ah yes. In that case, let's update the exception message above to match what we have here (which is more useful, I think).

**Comment by enocom** [comment]
Side note: does this issue fix all the Auto IAM AuthN flaky tests?

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java (hunk 1 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:255]: Fixed.

File: core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java (hunk 2 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java:329]: Test added. I refactored the retry logic into its own implementation of Callable called RetryingCallable so that it could be tested.

**Comment by hessjcg** [comment]
Yes, this fixes all the flakey tests.

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java [hunk 3]
```diff
@@ -162,8 +161,11 @@ public AccessToken refreshAccessToken() throws IOException {
         }
       };
     }
-
-    throw new RuntimeException("Not supporting credentials of type " + source.getClass().getName());
+    throw new RuntimeException(
+        String.format(
+            "[%s] Unable to connect via automatic IAM authentication: "
+                + "Not supporting credentials of type %s",
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:167]: Should this be "Unsupported credentials of type ..."? "Not supporting" sounds odd.

File: core/src/main/java/com/google/cloud/sql/core/RetryingCallable.java [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+import java.util.concurrent.ThreadLocalRandom;
+
+/**
+ * RetryLogic attempts to call a Callable multiple times, sleeping between failed attempts. The
+ * sleep duration is chosen randomly in the range [sleepDuration, sleepDuration * 2] to avoid
+ * causing a thundering herd of requests on failure.
+ *
+ * @param <T> the result type of the Callable.
+ */
+public class RetryingCallable<T> implements Callable<T> {
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/RetryingCallable.java:30]: Should this be public?

File: core/src/main/java/com/google/cloud/sql/core/RetryingCallable.java [hunk 5]
```diff
@@ -0,0 +1,93 @@
...
+    }
+    this.call = call;
+    this.retryCount = retryCount;
+    this.sleepDuration = sleepDuration;
+  }
+
+  @Override
+  public T call() throws Exception {
+
+    for (int i = retryCount - 1; i >= 0; i--) {
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/RetryingCallable.java:64]: Why the count down instead of the usual count up?

File: core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java [hunk 6]
```diff
@@ -318,6 +319,32 @@ private Certificate fetchEphemeralCertificate(
...
+
+    RetryingCallable<OAuth2Credentials> c =
+        new RetryingCallable<>(refresh, 3, Duration.ofSeconds(3));
+    try {
+      c.call();
+    } catch (IOException e) {
+      throw e;
+    } catch (Exception e) {
+      throw new RuntimeException(
+          "Unexpected exception while attempting to refresh oauth credentials", e);
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java:344]: s/oauth/OAuth2/

File: core/src/main/java/com/google/cloud/sql/core/RetryingCallable.java [hunk 7]
```diff
@@ -0,0 +1,93 @@
...
+
+  /**
+   * Construct a new RetryLogic.
+   *
+   * @param call the callable that should be retried
+   * @param retryCount the number of times to retry
+   * @param sleepDuration the duration wait after a failed attempt.
+   */
+  public RetryingCallable(Callable<T> call, int retryCount, Duration sleepDuration) {
+    if (retryCount <= 0) {
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/RetryingCallable.java:47]: Shall we test all these error conditions?

File: core/src/test/java/com/google/cloud/sql/core/RetryingCallableTest.java [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+
+import java.time.Duration;
+import java.util.concurrent.atomic.AtomicInteger;
+import org.junit.Assert;
+import org.junit.Test;
+
+public class RetryingCallableTest {
+  @Test
+  public void testNoRetryRequired() throws Exception {
+    RetryingCallable<Integer> r = new RetryingCallable<>(() -> 1, 5, Duration.ofSeconds(1));
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/RetryingCallableTest.java:29]: Do we need to wait a full second in test between retries?

File: core/src/main/java/com/google/cloud/sql/core/RetryingCallable.java [hunk 9]
```diff
@@ -0,0 +1,93 @@
...
+ * RetryLogic attempts to call a Callable multiple times, sleeping between failed attempts. The
+ * sleep duration is chosen randomly in the range [sleepDuration, sleepDuration * 2] to avoid
+ * causing a thundering herd of requests on failure.
+ *
+ * @param <T> the result type of the Callable.
+ */
+public class RetryingCallable<T> implements Callable<T> {
+
+  /** The callable that should be retried. */
+  private final Callable<T> call;
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/RetryingCallable.java:33]: nit: Let's just match the class name generally. So this would be `callable`.

File: core/src/test/java/com/google/cloud/sql/core/BadConnectionFactory.java [hunk 10]
```diff
@@ -0,0 +1,32 @@
...
+
+    @Override
+    public void addHeader(String name, String value) throws IOException {
+      // do nothing.
+    }
+
+    @Override
+    public LowLevelHttpResponse execute() throws IOException {
+      try {
+        Thread.sleep(10000);
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/BadConnectionFactory.java:26]: If we're just going to throw a Socket timeout exception, shall we just skip the sleep here?

**Comment by enocom** [comment]
This PR adds a retry for fetching the OAuth2 token which is used exclusively in Auto IAM AuthN. Why do you think it will fix the integration tests that aren't using Auto IAM AuthN?

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java (hunk 3 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:167]: fixed.

File: core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java (hunk 6 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java]: fixed.

File: core/src/test/java/com/google/cloud/sql/core/BadConnectionFactory.java [hunk 11]
```diff
@@ -0,0 +1,32 @@
...
+import java.net.SocketTimeoutException;
+
+public class BadConnectionFactory extends HttpTransport {
+
+  @Override
+  protected LowLevelHttpRequest buildRequest(String method, String url) throws IOException {
+    return new FailToConnectRequest();
+  }
+
+  private class FailToConnectRequest extends LowLevelHttpRequest {
```
[the remark this answers is not in the document]
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/BadConnectionFactory.java]: Fixed.

File: core/src/test/java/com/google/cloud/sql/core/BadConnectionFactory.java (hunk 10 above)
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/BadConnectionFactory.java]: Fixed.

File: core/src/test/java/com/google/cloud/sql/core/RetryingCallableTest.java (hunk 8 above)
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/RetryingCallableTest.java]: Changed to 100ms.

File: core/src/main/java/com/google/cloud/sql/core/RetryingCallable.java (hunk 7 above)
Comment (enocom) [reply core/src/main/java/com/google/cloud/sql/core/RetryingCallable.java:47]: Let's put some tests around all this behavior. Should be simple to test.

**Review by enocom — CHANGES_REQUESTED** [review]
LGTM. I'd like to see us add tests for the various error conditions in RetryingCallable's constructor before merging this.

**Comment by hessjcg** [comment]
Added tests for RetryingCallable constructor illegal arguments.

**Review by enocom — APPROVED** [review]
