### PR TITLE
fix: remove race condition bug in refresh logic

### LINKED ISSUE #1159: sql.mysql.JdbcMysqlJ8IamAuthIntegrationTests: pooledConnectionTest failed
Note: #1081 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 4293451fbf5249fed80da03c54fa83417180bca1
buildURL: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4186937144
status: failed
<details><summary>Test output</summary><br><pre>java.lang.NullPointerException: Cannot invoke "com.zaxxer.hikari.HikariDataSource.getConnection()" because "this.connectionPool" is null
	at com.google.cloud.sql.mysql.JdbcMysqlJ8IamAuthIntegrationTests.dropTableIfPresent(JdbcMysqlJ8IamAuthIntegrationTests.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></details>

### LINKED ISSUE #1209: sql.mysql.JdbcMysqlJ5IntegrationTests: pooledConnectionTest failed
Note: #1128 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 06afee117a384cd91ead58fa0ddb77ac8aa7f687
buildURL: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4418358329
status: failed
<details><summary>Test output</summary><br><pre>java.lang.NullPointerException: Cannot invoke "com.zaxxer.hikari.HikariDataSource.getConnection()" because "this.connectionPool" is null
	at com.google.cloud.sql.mysql.JdbcMysqlJ5IntegrationTests.dropTableIfPresent(JdbcMysqlJ5IntegrationTests.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
</pre></details>

### LINKED ISSUE #1314: `bad_certificate` errors intermittently preventing connection to cloud sql
### Bug Description

When using hikari database connection pooling with cloud sql we're seeing intermittently, usually after a few hours an issue where connections become unavailable with a `bad_certificate` error. We see this with mysql and postgres cloud sql connections authenticating with username/password, and differing hikari configurations (most set with the default hikari config of maxLifetime of 30 mins).

### Example code (or command)

_No response_

### Stacktrace

```bash
....
Caused by: java.sql.SQLTransientConnectionException: HikariPool-3 - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at com.company.config.CloseableDataSourceHikari.getConnection(CloseableDataSourceHikari.java:25)
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:319)
	... 18 common frames omitted
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
	at org.postgresql.Driver.makeConnection(Driver.java:443)
	at org.postgresql.Driver.connect(Driver.java:297)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:358)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at com.google.cloud.sql.core.CoreSocketFactory.createSslSocket(CoreSocketFactory.java:339)
	at com.google.cloud.sql.core.CoreSocketFactory.connect(CoreSocketFactory.java:201)
	at com.google.cloud.sql.postgres.SocketFactory.createSocket(SocketFactory.java:77)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	... 15 common frames omitted
```

### Steps to reproduce?

1. Connect to cloud sql either postgres or mysql using username/password ("Allow only SSL connections" does not need to be enabled in cloud sql)
2. Let your app run for awhile usually the issue presents itself in a few hours or so. Unable to reproduce myself locally with differing hikari settings.

### Environment

1. OS type and version: Docker Linux arm64
2. Java SDK version: 17
3. Cloud SQL Java Socket Factory version: postgres-socket-factory 1.11.2  - jdbi-cloudsql 2.3.5

### Additional Details

My initial reaction was it looks similar to the closed issue here https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/472

And is possibly related to this [Draft PR](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/1307). 

My colleague has opened an incident with google support already for this issue, but I think it might be worthwhile to open an issue here too. Case 45213975

### PR DESCRIPTION
**Pull request by hessjcg**
Update the logic in forceRefresh() to reduce the churn on the thread pool when the certificate refresh API calls are failing. 

New forceRefresh() logic ensures that:

- Only 1 refresh cycle may run at a time. 
- If a refresh cycle is in progress, then it will not be canceled until it succeeds.

Add new test cases to validate race conditions, deadlocks, and concurrency.

Add additional logging to help diagnose production problems with certificate refresh.

Related to #1314

Fixes #1209 
Fixes #1159

### CODE REVIEW

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java [hunk 1]
```diff
@@ -57,8 +57,7 @@ class CloudSqlInstance {
   private final ListenableFuture<KeyPair> keyPair;
   private final Object instanceDataGuard = new Object();
   // Limit forced refreshes to 1 every minute.
-  private final RateLimiter<Object> forcedRenewRateLimiter =
-      RateLimiter.burstyBuilder(2, Duration.ofSeconds(30)).build();
+  private final RateLimiter<Object> forcedRenewRateLimiter;
```
Comment (hessjcg) [inline core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:60]: I added constructor that allows tests to pass in the rate limiter so that we could make the tests run faster.

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java [hunk 2]
```diff
@@ -159,6 +181,13 @@ String getPreferredIp(List<String> preferredTypes) {
    */
   void forceRefresh() {
     synchronized (instanceDataGuard) {
+      // Don't force a refresh until the current forceRefresh operation
```
Comment (hessjcg) [inline core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:184]: Balk if a forceRefresh() is in progress and has not yet succeeded.

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java [hunk 3]
```diff
@@ -228,4 +258,20 @@ private InstanceData performRefresh() throws InterruptedException, ExecutionExce
   SslData getSslData() {
     return getInstanceData().getSslData();
   }
+
+  ListenableFuture<InstanceData> getNext() {
```
Comment (hessjcg) [inline core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:262]: This is for testing.

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java [hunk 4]
```diff
@@ -83,11 +85,31 @@ class CloudSqlInstance {
...
+        instanceDataSupplier,
+        authType,
+        tokenSourceFactory,
+        executor,
+        keyPair,
+        RateLimiter.burstyBuilder(2, Duration.ofSeconds(30)).build());
+  }
+
+  /** A constructor for use in tests that allows the caller to set the RateLimiter. */
+  CloudSqlInstance(
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:99]: Let's just update the constructor to pass in the rate limiter. We don't need two constructors.

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java [hunk 5]
```diff
@@ -159,6 +181,13 @@ String getPreferredIp(List<String> preferredTypes) {
...
     synchronized (instanceDataGuard) {
+      // Don't force a refresh until the current forceRefresh operation
+      // has produced a successful refresh.
+      if (forceRefreshRunning) {
+        return;
+      }
+
+      forceRefreshRunning = true;
       nextInstanceData.cancel(false);
       if (nextInstanceData.isCancelled()) {
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:192]: Shall we remove this if block and always schedule a next refresh since we also always call cancel? This after having observed that cancel doesn't always work as we might think.

File: core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java [hunk 6]
```diff
@@ -120,9 +120,11 @@ public static synchronized CoreSocketFactory getInstance() {
   @VisibleForTesting
   // Returns a listenable, scheduled executor that exits upon shutdown.
   static ListeningScheduledExecutorService getDefaultExecutor() {
-    // TODO(kvg): Figure out correct way to determine number of threads
+    // Set the number of threads to 8. This should be enough threads that most users
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java:123]: Let's split this out into a separate PR since it's technically the fix of the bug.

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java (hunk 2 above)
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:184]: Would you mind sending a PR with all the logging added here? https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/tree/enocom-debug It was quite useful for debugging and would be good to have in the future.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 7]
```diff
@@ -0,0 +1,351 @@
...
+import org.junit.Test;
+
+public class CloudSqlInstanceConcurrencyTest {
+  private static final long start = System.currentTimeMillis();
+
+  private static final Logger logger =
+      Logger.getLogger(CloudSqlInstanceConcurrencyTest.class.getName());
+
+  static {
+    ConsoleHandler handler =
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:44]: Is this a dev artifact?

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 8]
```diff
@@ -0,0 +1,351 @@
...
+  @Test
+  public void testCloudSqlInstanceConcurrency() throws Exception {
+    // Run the test 10 times to ensure we don't have race conditions
+    for (int i = 0; i < 10; i++) {
+      runConcurrencyTest();
+    }
+  }
+
+  @Test
+  public void testBasicHappyPath() throws Exception {
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:150]: Rather than happy path, let's make it descriptive: "testCloudSqlInstanceDoesXYZ"

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 9]
```diff
@@ -0,0 +1,351 @@
...
+            "a:b:c",
+            supplier,
+            AuthType.PASSWORD,
+            new TestCredentialFactory(),
+            executor,
+            keyPairFuture,
+            newRateLimiter());
+
+    assertThat(supplier.counter.get()).isEqualTo(0);
+    Thread.sleep(500);
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:167]: How can we avoid a sleep to ensure our test remains solid?

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 10]
```diff
@@ -0,0 +1,351 @@
...
+    SslData data = instance.getSslData();
+    assertThat(data).isNotNull();
+  }
+
+  @Test
+  public void testPermanentFailure() throws Exception {
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:173]: Would you expand the description here? I'm not sure at a glance what we're testing here.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 11]
```diff
@@ -0,0 +1,351 @@
...
+    for (CloudSqlInstance inst : instances) {
+      if (inst.getNext().isDone() && inst.getCurrent().isDone()) {
+        logger.warning("No future scheduled thing for instance " + inst.getInstanceName());
+        brokenLoop++;
+      }
+    }
+    assertThat(brokenLoop).isEqualTo(0);
+  }
+
+  private ListeningScheduledExecutorService newTestExecutor() {
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:338]: Shall we use the same executor as in CoreSocketFactory?

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 12]
```diff
@@ -0,0 +1,351 @@
...
+        allData2.get();
+      } catch (Exception e) {
+      }
+      assertThat(supplier.counter.get()).isEqualTo(2 + i);
+      Thread.sleep(100);
+    }
+  }
+
+  @Test
+  public void testForceRefreshDeadlock() throws Exception {
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:267]: I think we're testing that we don't deadlock here is that right?

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 13]
```diff
@@ -0,0 +1,351 @@
...
+
+    // Get SSL Data for each instance, forcing the first refresh
+    instances.forEach(i -> i.getSslData());
+
+    assertThat(supplier.counter.get()).isEqualTo(instanceCount);
+
+    List<Thread> threads =
+        instances.stream()
+            .map(
+                (inst) -> {
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:299]: Could we pull this lambda out into a method to make its purpose clear?

**Review by enocom — CHANGES_REQUESTED** [review]

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 12 above)
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java]: Fixed. Renamed testForceRefreshRaceDoesNotCauseADeadlock for clarity.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 7 above)
Comment (enocom) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:44]: I think you're looking for this: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/pom.xml#L197

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 13 above)
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java]: Done.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 11 above)
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java]: Done. Yes. But then tests will fail until #1391 is merged.

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java (hunk 4 above)
Comment (enocom) [reply core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:99]: As a rule, I think we shouldn't be making test only APIs. And parameterizing the rate limiter is actually useful. Imagine if we wanted to expose rate limiting knobs to the user, or configure instances with different rate limits.

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java [hunk 14]
```diff
@@ -159,20 +181,19 @@ String getPreferredIp(List<String> preferredTypes) {
...
+      // Don't force a refresh until the current forceRefresh operation
+      // has produced a successful refresh.
+      if (forceRefreshRunning) {
+        return;
       }
+
+      forceRefreshRunning = true;
+      nextInstanceData.cancel(false);
+      logger.fine(
+          "Force Refresh: the next refresh operation was cancelled."
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:193]: Let's add the instance to the log message in leading brackets as we've done elsewhere. You might even make a convenience method for it that all methods (or even classes) can use.

File: core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java [hunk 15]
```diff
@@ -152,14 +151,22 @@ public InstanceData getInstanceData(
                             .orElse(x509Certificate.getNotAfter());
                   }
 
+                  logger.info(
+                      String.format(
+                          "[%s %d] INSTANCE DATA DONE",
+                          instanceName, Thread.currentThread().getId()));
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java:157]: Let's leave the thread ID off -- unless it's worth keeping?

Comment (enocom) [reply core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java:157]: ditto with below

File: core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java [hunk 16]
```diff
@@ -152,14 +151,22 @@ public InstanceData getInstanceData(
                             .orElse(x509Certificate.getNotAfter());
                   }
 
+                  logger.info(
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java:154]: These should all be logger.fine

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java (hunk 4 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java]: Fixed. I'm not convinced, but it's not worth arguing about.

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java (hunk 14 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java]: Fixed.

File: core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java (hunk 16 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java]: Fixed.

File: core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java (hunk 15 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java]: Fixed.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 7 above)
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java]: I removed this. I'll use the logging file instead.

**Review by enocom — CHANGES_REQUESTED** [review]
I think we can test this directly. Let's talk tomorrow about how to do that.

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java [hunk 17]
```diff
@@ -68,6 +67,13 @@ class CloudSqlInstance {
   @GuardedBy("instanceDataGuard")
   private ListenableFuture<InstanceData> nextInstanceData;
 
+  @GuardedBy("instanceDataGuard")
+  private boolean forceRefreshRunning;
+
+  static final RateLimiter defaultRateLimiter() {
```
[the remark this answers is not in the document]
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:73]: Done.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 18]
```diff
@@ -0,0 +1,315 @@
...
+import org.junit.Test;
+
+public class CloudSqlInstanceConcurrencyTest {
+
+  private static final Logger logger =
+      Logger.getLogger(CloudSqlInstanceConcurrencyTest.class.getName());
+
+  private static class TestDataSupplier implements InstanceDataSupplier {
+
+    private final boolean flakey;
```
[the remark this answers is not in the document]
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java]: Fixed.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 19]
```diff
@@ -0,0 +1,315 @@
...
+        new InstanceData(
+            new Metadata(
+                ImmutableMap.of(
+                    "PUBLIC", "10.1.2.3",
+                    "PRIVATE", "10.10.10.10",
+                    "PSC", "abcde.12345.us-central1.sql.goog"),
+                null),
+            new SslData(null, null, null),
+            Date.from(Instant.now().plus(1, ChronoUnit.HOURS)));
+    private final ListeningScheduledExecutorService executor;
```
[the remark this answers is not in the document]
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java]: Fixed.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 20]
```diff
@@ -0,0 +1,315 @@
...
+    @Override
+    public InstanceData getInstanceData(
+        CloudSqlInstanceName instanceName,
+        AccessTokenSupplier accessTokenSupplier,
+        AuthType authType,
+        ListeningScheduledExecutorService executor,
+        ListenableFuture<KeyPair> keyPair)
+        throws ExecutionException, InterruptedException {
+
+      ListenableFuture<InstanceData> f =
```
[the remark this answers is not in the document]
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:85]: Done.

**Review by enocom — COMMENTED** [review]
I see the new tests here add ~1 minute to our build. I think there's a way we can test this without the time increase. Let's talk about how when you're ready.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 21]
```diff
@@ -0,0 +1,311 @@
...
+              supplier,
+              AuthType.PASSWORD,
+              new TestCredentialFactory(),
+              executor,
+              keyPairFuture,
+              newRateLimiter()));
+    }
+
+    // Get SSL Data for each instance, forcing the first refresh to complete.
+    instances.forEach(i -> i.getSslData());
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:256]: This can be simplified to a lambda reference.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 22]
```diff
@@ -0,0 +1,311 @@
...
+            "a:b:c",
+            supplier,
+            AuthType.PASSWORD,
+            new TestCredentialFactory(),
+            executor,
+            keyPairFuture,
+            newRateLimiter());
+
+    Thread.sleep(500);
+    Assert.assertThrows(RuntimeException.class, () -> instance.getSslData());
```
[the remark this answers is not in the document]
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:248]: The key difference is that this one throws an exception from within a scheduled executor task. This used to exacerbate the deadlock problem.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 21 above)
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java]: Fixed.

**Review by hessjcg — COMMENTED** [review]
I updated the CloudSqlInstanceConcurrencyTest based on comments.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 23]
```diff
@@ -0,0 +1,331 @@
...
+    public HttpRequestInitializer create() {
+      return this;
+    }
+
+    public void initialize(HttpRequest var1) throws IOException {
+      // do nothing
+    }
+  }
+
+  @Test(timeout = 45000)
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:116]: Do we still need this?

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 24]
```diff
@@ -0,0 +1,311 @@
...
+        allData2.get();
+      } catch (Exception e) {
+      }
+      assertThat(supplier.counter.get()).isEqualTo(2 + i);
+      Thread.sleep(100);
+    }
+  }
+
+  @Test
+  public void testCloudSqlInstanceCorrectlyRefreshesInstanceData() throws Exception {
```
[the remark this answers is not in the document]
Comment (enocom) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:193]: If this wasn't used to drive out the bug, I think we should check that we have similar coverage elsewhere (I believe we do) and omit this one here.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 22 above)
[the remark this answers is not in the document]
Comment (enocom) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:248]: Is this behavior covered by `testCloudSqlInstanceRefreshesConsistentlyWithoutRaceConditions`? It looks like a duplicate test to my eyes.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 25]
```diff
@@ -0,0 +1,331 @@
...
+            keyPairFuture,
+            newRateLimiter());
+
+    Thread.sleep(500);
+    Assert.assertThrows(RuntimeException.class, () -> instance.getSslData());
+    // Note: refresh attempts will continue the background. This instance.getSslData() throws an
+    // exception after the first refresh attempt fails.
+  }
+
+  @Test(timeout = 45000) // 45 seconds timeout in case of deadlock
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:253]: Same thing here. Do we need this?

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 23 above)
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:116]: Yes. If there is a deadlock, then the test will only fail with a timeout. So we should leave this in just incase we cause a deadlock again in the future.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 26]
```diff
@@ -0,0 +1,311 @@
...
+            new TestCredentialFactory(),
+            executor,
+            keyPairFuture,
+            newRateLimiter());
+    assertThat(supplier.counter.get()).isEqualTo(0);
+
+    // Attempt to retrieve data, ensure we wait for success
+    ListenableFuture<List<Object>> allData =
+        Futures.allAsList(
+            executor.submit(instance::getSslData),
```
[the remark this answers is not in the document]
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:137]: It just needs to be more than one. And three is a magic number.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 24 above)
[the remark this answers is not in the document]
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:193]: We do not have exactly this same coverage elsewhere. This was used to drive out the bug. I would like to leave this here.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 22 above)
[the remark this answers is not in the document]
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:248]: This test has a single CloudSqlInstance and ensures that it successfully refreshes the correct number of times. Thus proving that the balking behavior of forceRefresh() works right. 

`testCloudSqlInstanceRefreshesConsistentlyWithoutRaceConditions` tries to cause a race condition and deadlock with multiple CloudSqlInstances and many more threads. It is fundimentally a different test. 

While developing, if there was a bug in my code, one of these tests would fail and the other would pass. So I think they are both useful.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 25 above)
Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:253]: Yes. If this test deadlocks, then the test will fail with a timeout. Otherwise it will hang indefinitely.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 23 above)
Comment (enocom) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:116]: Do we really want to wait 45 seconds before failing? What's the default value?

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 26 above)
[the remark this answers is not in the document]
Comment (enocom) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:137]: Let's use two in that case, and add a comment. I'm asking for my personal interest, but also for future readers who will wonder the same.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 27]
```diff
@@ -0,0 +1,331 @@
...
+          // Wait for all to finish.
+          allData2.get();
+
+          // If they all succeeded, then continue with the test.
+          break;
+        } catch (ExecutionException e) {
+          // We expect some of these to throw an exception indicating that the refresh cycle
+          // got a failed attempt. When they throw an exception,
+          // sleep and try again. This shows that the refresh cycle is working.
+          Thread.sleep(100);
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:181]: Shall we add a log statement here too?

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 24 above)
[the remark this answers is not in the document]
Comment (enocom) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:193]: I think this test is just the same as [this test](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java#L87). In my view, the assertions don't communicate what different behavior we have.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java [hunk 28]
```diff
@@ -0,0 +1,331 @@
...
+        new CloudSqlInstance(
+            "a:b:c",
+            supplier,
+            AuthType.PASSWORD,
+            new TestCredentialFactory(),
+            executor,
+            keyPairFuture,
+            newRateLimiter());
+
+    Thread.sleep(500);
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:247]: Why the sleep here?

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 22 above)
[the remark this answers is not in the document]
Comment (enocom) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:248]: Right now this test proves that the CloudSqlInstance calls the underlying InstanceDataSupplier, which is a variation of [this test](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java#L65). If you'd like to test that force refresh functions correctly, then I'd expect a call that fails, a force refresh, and then a call that succeeeds.

File: core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java (hunk 25 above)
Comment (enocom) [reply core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java:253]: Same here -- can we bump this number down? Can we rely on the default value? I assume the test framework does a default timeout (I think it's 30s).

**Review by enocom — APPROVED** [review]
