### PR TITLE
test: Fix flaky test in lazy refresh, fixes #1980.

### LINKED ISSUE #1980: sql.core.LazyRefreshStrategyTest: testCloudSqlRefreshesExpiredData failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 2c8ae93b49c65bb0ed907f1ee7f49d69c91e6388
buildURL: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/9098621459
status: failed

### PR DESCRIPTION
**Pull request by hessjcg**
Java 8 thread and timing is not as reliable as newer JVMs. This introduces an extra small delay in the tests 
that test the expiration of the data so that it works reliably in Java 8.

### CODE REVIEW

File: core/src/test/java/com/google/cloud/sql/core/LazyRefreshStrategyTest.java [hunk 1]
```diff
@@ -106,13 +103,19 @@ public void testCloudSqlRefreshesExpiredData() throws Exception {
...
+
+  private static void waitForExpiration(ExampleData initialData) throws InterruptedException {
     // Wait for the instance to expire
     while (Instant.now().isBefore(initialData.getExpiration())) {
       Thread.sleep(10);
     }
-
-    assertThat(r.getConnectionInfo(TEST_TIMEOUT_MS)).isSameInstanceAs(data);
-    assertThat(refreshCount.get()).isEqualTo(2);
+    // Introduce a little more delay to allow for Java 8
```
Comment (enocom) [inline core/src/test/java/com/google/cloud/sql/core/LazyRefreshStrategyTest.java:117]: Could we elaborate on the comment here? Why does JAva 8 need more time?

Comment (enocom) [reply core/src/test/java/com/google/cloud/sql/core/LazyRefreshStrategyTest.java:117]: Alternatively, could we make the sleep above be for 100ms instead?

Comment (hessjcg) [reply core/src/test/java/com/google/cloud/sql/core/LazyRefreshStrategyTest.java]: I updated this to make the comment a little more explicit.
