### PR TITLE
chore: fix lint warnings

### LINKED ISSUE #1460: Correct all lint warnings in build
Also, we should consider failing the build instead of just warning on lint problems.

### PR DESCRIPTION
**Pull request by ttosta-google**
Fixes #1460

Notes:

* Now the build fails on warnings.
* `Thread.yield();` triggers the warning [ThreadPriorityCheck](https://errorprone.info/bugpattern/ThreadPriorityCheck). So I replaced it by `Thread.sleep(0);` as they may call same system calls in some platforms. Please let me know if you have any other suggestions.

### CODE REVIEW

File: jdbc/sqlserver/src/main/java/com/google/cloud/sql/sqlserver/SocketFactory.java [hunk 1]
```diff
@@ -46,21 +48,23 @@ public class SocketFactory extends javax.net.SocketFactory {
    * connections to a Cloud SQL instance.
    */
   public SocketFactory(String socketFactoryConstructorArg) throws UnsupportedEncodingException {
-    String[] s = socketFactoryConstructorArg.split("\\?");
-    this.props.setProperty(CoreSocketFactory.CLOUD_SQL_INSTANCE_PROPERTY, s[0]);
-    if (s.length == 2 && s[1].length() > 0) {
-      String[] queryParams = s[1].split("&");
+    List<String> s = Splitter.on('?').splitToList(socketFactoryConstructorArg);
```
Comment (enocom) [inline jdbc/sqlserver/src/main/java/com/google/cloud/sql/sqlserver/SocketFactory.java:51]: Do we have any unit tests covering this code?

We should ensure we have thorough testing of this code before changing it here, just out of caution. Also, once we have those tests in place, we should clean this code up -- on the surface it looks more complicated than it needs to be.

Comment (ttosta-google) [reply jdbc/sqlserver/src/main/java/com/google/cloud/sql/sqlserver/SocketFactory.java:51]: Yes, we have unit tests for this code in [JdbcSqlServerUnitTests.java](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/jdbc/sqlserver/src/test/java/com/google/cloud/sql/sqlserver/JdbcSqlServerUnitTests.java).

I will create a new issue to refactor this code.

**Review by enocom — APPROVED** [review]
LGTM

Could we port the fail on lint warnings to AlloyDB Java too?
