### PR TITLE
fix: Lazy refresh should refresh tokens 4 minutes before expiration.

### LINKED ISSUE #2059: Unable to connect to CloudSQL databases after certificates expire, application can't recover
### Bug Description

Some of our applications are unable to connect to their CloudsQL database after running for a few days. They never recover until we restart them. We've enabled debug logging and suspect a problem with refreshing certificates.

We see that all applications continuously verify the certificate expiry:

```
[bolcom-pro-sre-health-538:europe-west4:sre-health] Now = 2024-07-30T09:04:39.959408416Z, Current client certificate expiration = 2024-07-30T10:04:14.941Z
```

At some point in time we see a refresh operation scheduled:

```
Jul 30, 2024 @ 11:04:39.553 DEBUG com.google.cloud.sql.core.RefreshAheadStrategy [bolcom-pro-sre-health-538:europe-west4:sre-health] Refresh Operation: Next operation scheduled at 2024-07-30T10:00:14Z.
```

Most applications then refresh the certificate at the scheduled time, but a few applications fail to do this and break as seen above.

In the logs below it looks like the refresh never happened at 10:00:14Z. Or at least that an old certificate is still lingering. Because at 12:05:17 the applications tries to use the certificate that expired 2 hours ago.

```
Jul 30, 2024 @ 12:05:17.156 DEBUG com.google.cloud.sql.core.RefreshAheadStrategy [bolcom-pro-sre-health-538:europe-west4:sre-health] Client certificate has expired. Starting next refresh operation immediately.
Jul 30, 2024 @ 12:05:17.156 DEBUG com.google.cloud.sql.core.RefreshAheadStrategy [bolcom-pro-sre-health-538:europe-west4:sre-health] Now = 2024-07-30T10:05:17.156356729Z, Current client certificate expiration = 2024-07-30T10:04:14.941Z
```
It looks like refreshing the certificate fails, or at least the application is still using the wrong one. As after connections to the database fail.

```
Jul 30, 2024 @ 12:05:17.157 DEBUG com.google.cloud.sql.core.Connector [10.25.8.40] Connecting to instance.
Jul 30, 2024 @ 12:05:17.172 DEBUG com.google.cloud.sql.core.Connector [10.25.8.40] Connected to instance successfully.
Jul 30, 2024 @ 12:05:17.174 DEBUG com.zaxxer.hikari.pool.HikariPool HikariPool-1 - Cannot acquire connection from data source org.postgresql.util.PSQLException: The connection attempt failed. at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358) at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273) at org.postgresql.Driver.makeConnection(Driver.java:446) at org.postgresql.Driver.connect(Driver.java:298) at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137) at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360) at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at java.base/java.lang.Thread.run(Thread.java:1583) caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130) at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117) at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:365) at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:287) at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:204) at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1509) at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1480) at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066) at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162) at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129) at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114) at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74) at org.postgresql.core.PGStream.receiveChar(PGStream.java:467) at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:683) at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:207) at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262) ... 14 common frames elided
Jul 30, 2024 @ 12:05:17.174 DEBUG com.zaxxer.hikari.pool.PoolBase HikariPool-1 - Failed to create/setup connection: The connection attempt failed.
```

We haven't been able to identify what is different between applications that work and fail. In some cases even copies of applications (like one for testing and one for production) behave differently. With one working flawlessly for months, while the other one fails every few days. One thing I have noticed is that these applications all have a relatively low load and can idle for hours before a new database interaction happens. But I'm not sure if that is a clue or just an unrelated factor. 

We are currently using the following library versions:
- spring-cloud-gcp 5.4.1
- spring-boot 3.3.1
- HikariCP 5.1.0
- com.google.cloud.sql:jdbc-socket-factory-core:jar:1.18.0

We did not observe the issue when using:
- spring-cloud-gcp 4.9.4
- spring-boot 3.1.9
- HikariCP 5.0.1
- com.google.cloud.sql:jdbc-socket-factory-core:jar:1.14.1

We started seeing the issue when using: 
- spring-cloud-gcp 5.4.0
- spring-boot 3.2.6
- HikariCP 5.0.1
- com.google.cloud.sql:jdbc-socket-factory-core:jar:1.18.0

I haven't been able to narrow it down further yet. 

We found the following issue: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/1314 which looks similar, but was fixed in `jdbc-socket-factory-core:jar:1.13.1`.  We are currently using 1.18.0.

### Example code (or command)

_No response_

### Stacktrace

```bash
om.zaxxer.hikari.pool.HikariPool HikariPool-1 - Cannot acquire connection from data source org.postgresql.util.PSQLException: The connection attempt failed. at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358) at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273) at org.postgresql.Driver.makeConnection(Driver.java:446) at org.postgresql.Driver.connect(Driver.java:298) at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137) at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360) at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at java.base/java.lang.Thread.run(Thread.java:1583) caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130) at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117) at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:365) at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:287) at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:204) at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1509) at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1480) at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066) at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:162) at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:129) at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114) at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:74) at org.postgresql.core.PGStream.receiveChar(PGStream.java:467) at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:683) at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:207) at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262) ... 14 common frames elided
Jul 30, 2024 @ 12:05:17.174 DEBUG com.zaxxer.hikari.pool.PoolBase HikariPool-1 - Failed to create/setup connection: The connection attempt failed.
```

### Steps to reproduce?

Unfortunately I don't have a good reproduction path. The issue seems to be consistently happening with only a few of our applications. Only happens after working well for a couple of days. 

### Environment

1. OS: Debian 12, running on Google Kubernetes Engine
2. JRE: Azul Zulu 21
3. Cloud SQL Java Socket Factory version: 1.18.0

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by hessjcg**
Added a 4 minute buffer to refreshing tokens and certificates to avoid creating race condition that would allow the connector to create an ephemeral certificate with an expired auth token. 

Now, IAM auth tokens are now refreshed 4 minutes before they token expire. Also, the Lazy Refresh Strategy will refresh the client certificate 4 minutes before the expiration of the certificate and the IAM auth token. 

This should mitigate some of the strange certificate expiration errors commonly found in Cloud Run, see: #2059

### CODE REVIEW

**Comment by jackwotherspoon** [comment]
> This may mitigate some token expiration problems in Cloud Run.
> 
> Fixes https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/2059

We don't know for sure that this will fix the above issue right? We should probably mark this as "Related to #2509" and have it tested in the wild first before marking as fixed. Thoughts?

File: core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java [hunk 1]
```diff
@@ -135,6 +134,28 @@ public Optional<AccessToken> get() throws IOException {
...
+    // if the token does not exist, or if the token expires in less than 4 minutes, refresh it.
+    if (credentials.getAccessToken() == null) {
+      logger.debug("Current IAM Auth Token is not set. Refreshing the token.");
+      credentials.refresh();
+    } else if (credentials.getAccessToken().getExpirationTime() != null
+        && credentials
+            .getAccessToken()
+            .getExpirationTime()
+            .toInstant()
+            .minus(4, ChronoUnit.MINUTES)
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java:152]: Do we have a constant for this value somewhere? I think we should use it to avoid future mistakes in buffering.

**Review by enocom — COMMENTED** [review]
LGTM. One small nit.

File: core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java (hunk 1 above)
Comment (jackwotherspoon) [reply core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java:152]: ➕

File: core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java [hunk 2]
```diff
@@ -135,6 +134,28 @@ public Optional<AccessToken> get() throws IOException {
...
 
+  private static boolean isAccessTokenEmpty(GoogleCredentials credentials) {
+    return credentials.getAccessToken() == null
+        || "".equals(credentials.getAccessToken().getTokenValue());
+  }
+
+  private void refreshIfNearExpiration(GoogleCredentials credentials) throws IOException {
+    // if the token does not exist, or if the token expires in less than 4 minutes, refresh it.
+    if (credentials.getAccessToken() == null) {
+      logger.debug("Current IAM Auth Token is not set. Refreshing the token.");
```
Comment (jackwotherspoon) [inline core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java:145]: nit
```suggestion
      logger.debug("Current IAM AuthN Token is not set. Refreshing the token.");
```

File: core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java [hunk 3]
```diff
@@ -135,6 +134,28 @@ public Optional<AccessToken> get() throws IOException {
...
+      credentials.refresh();
+    } else if (credentials.getAccessToken().getExpirationTime() != null
+        && credentials
+            .getAccessToken()
+            .getExpirationTime()
+            .toInstant()
+            .minus(4, ChronoUnit.MINUTES)
+            .isBefore(Instant.now())) {
+      logger.debug("Current IAM Auth Token expires in less than 4 minutes. Refreshing the token.");
```
Comment (jackwotherspoon) [inline core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java:154]:
```suggestion
      logger.debug("Current IAM AuthN Token expires in less than 4 minutes. Refreshing the token.");
```

File: core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java (hunk 1 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java:152]: Good idea, yes. `RefreshCalculator.DEFAULT_REFRESH_BUFFER`

File: core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java (hunk 2 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java:145]: Fixed.

File: core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java (hunk 3 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java:154]: Fixed.

File: core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java [hunk 4]
```diff
@@ -135,6 +135,28 @@ public Optional<AccessToken> get() throws IOException {
     }
   }
 
+  private static boolean isAccessTokenEmpty(GoogleCredentials credentials) {
+    return credentials.getAccessToken() == null
+        || "".equals(credentials.getAccessToken().getTokenValue());
+  }
+
+  private void refreshIfNearExpiration(GoogleCredentials credentials) throws IOException {
```
Comment (sanmahapatra) [inline core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java:143]: nit: Since we also refresh for reasons other than expiry maybe a better name is refreshIfRequired or refreshIfNecessary or something similar.

**Review by sanmahapatra — APPROVED** [review]
LGTM

File: core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java (hunk 4 above)
Comment (hessjcg) [reply core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java:143]: Fixed.
