### PR TITLE
fix: throw exception on invalid IAM Authn config

### LINKED ISSUE #984: Throw exception on invalid Auto IAM AuthN Config
If a database engine doesn't support Auto IAM AuthN (i.e., MySQL, SQL Server), the connector should throw an error if a user has requested the feature.

Related: https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/issues/283.

### PR DESCRIPTION
**Pull request by shubha-rajan**
## Relevant issues:

- Fixes #984

### CODE REVIEW

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java [hunk 1]
```diff
@@ -482,6 +492,9 @@ private Metadata fetchMetadata() {
                     + "instance.",
                 connectionName));
       }
+      
+      checkDatabaseCompatibility(instanceMetadata, enableIamAuth, connectionName);
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:496]: nit: just inlining this method would match the checks above.

**Review by enocom — APPROVED** [review]

File: core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java (hunk 1 above)
Comment (shubha-rajan) [reply core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java:496]: I did it this way because it's easier to unit test. I think it'd actually be better if we pulled out the other checks and moved all the checks into a utils class, then tested that. It would increase our unit test coverage
