### PR TITLE
test: Simplify r2dbc integration tests.

### LINKED ISSUE #1262: sql.core.R2dbcMysqlIntegrationTests: pooledConnectionTest failed
Note: #1096 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: caaa6749788f0b436e52aaf66c9823560dc09f92
buildURL: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4710965932
status: failed
<details><summary>Test output</summary><br><pre>org.junit.runners.model.TestTimedOutException: test timed out after 20 seconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:837)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:999)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	at reactor.core.publisher.Flux.blockLast(Flux.java:2747)
	at com.google.cloud.sql.core.R2dbcMysqlIntegrationTests.pooledConnectionTest(R2dbcMysqlIntegrationTests.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
</pre></details>

### LINKED ISSUE #1272: sql.core.R2dbcPostgresIamAuthIntegrationTests: pooledConnectionTest failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 1a00fd2eeaac193151814ab517f395bb1430f501
buildURL: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4815259286
status: failed
<details><summary>Test output</summary><br><pre>java.lang.NullPointerException
	at com.google.cloud.sql.core.R2dbcPostgresIamAuthIntegrationTests.dropTableIfPresent(R2dbcPostgresIamAuthIntegrationTests.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
</pre></details>

### LINKED ISSUE #1273: sql.core.R2dbcPostgresIamAuthIntegrationTests: urlPooledConnectionTest failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 1a00fd2eeaac193151814ab517f395bb1430f501
buildURL: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/actions/runs/4815259286
status: failed
<details><summary>Test output</summary><br><pre>java.lang.NullPointerException
	at com.google.cloud.sql.core.R2dbcPostgresIamAuthIntegrationTests.dropTableIfPresent(R2dbcPostgresIamAuthIntegrationTests.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
</pre></details>

### PR DESCRIPTION
**Pull request by hessjcg**
Remove extraneous test code that created tables and inserted data. If the client 
can perform `select 1` or `select now`, the connection succeeded.

Fixes #1273 
Fixes #1262 
Fixes #1272

### CODE REVIEW

File: r2dbc/mysql/src/test/java/com/google/cloud/sql/core/R2dbcMysqlIamAuthIntegrationTests.java [hunk 1]
```diff
@@ -89,53 +86,17 @@ public void setUpPool() {
...
-        .blockLast();
-
-    String selectStmt = String.format("SELECT TITLE FROM %s ORDER BY ID", this.tableName);
-    List<String> books =
+    List<Object> rows =
         Mono.from(this.connectionPool.create())
-            .flatMapMany(connection -> connection.createStatement(selectStmt).execute())
-            .flatMap(result -> result.map((r, meta) -> r.get("TITLE", String.class)))
+            .flatMapMany(connection -> connection.createStatement("SELECT NOW() as TS").execute())
+            .flatMap(result -> result.map((r, meta) -> r.get("TS", Object.class)))
```
Comment (enocom) [inline r2dbc/mysql/src/test/java/com/google/cloud/sql/core/R2dbcMysqlIamAuthIntegrationTests.java:96]: `r.get("TS", Timestamp.class)`?

Comment (hessjcg) [reply r2dbc/mysql/src/test/java/com/google/cloud/sql/core/R2dbcMysqlIamAuthIntegrationTests.java:96]: It's not a Timestamp class actually. If this were a JDBC driver, it would be. However in R2DBC who knows what it is.

Comment (enocom) [reply r2dbc/mysql/src/test/java/com/google/cloud/sql/core/R2dbcMysqlIamAuthIntegrationTests.java:96]: Did you try `Instant.class`? Googling and that seems to work.

Comment (hessjcg) [reply r2dbc/mysql/src/test/java/com/google/cloud/sql/core/R2dbcMysqlIamAuthIntegrationTests.java]: I have now updated it to use Instant.
