### PR TITLE
fix: Call force refresh when r2dbc connection is invalid

### LINKED ISSUE #1719: cloud-sql-connector-r2dbc-postgres unable to connect to DB after SSL certificate rotation
### Bug Description

We are currently using  cloud-sql-connector-r2dbc-postgres v1.15.0 to connect from our java application to Cloud SQL using IAM authentication. The application normally works fine until when we rotate the DB SSL certificate, at which point the application is no longer able to connect to the database. If we rollback the certificate, the connection resumes just fine.

### Example code (or command)

```Java
pom.xml

<?xml version="1.0" encoding="UTF-8"?>

<project xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance xmlns=http://maven.apache.org/POM/4.0.0
         xsi:schemaLocation=http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.test.cloudsql</groupId>
    <artifactId>test-cloudsql-socketfactory</artifactId>
    <version>${revision}</version>
    <name>${project.artifactId}</name>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <revision>1.0-SNAPSHOT</revision>
    </properties>

    <dependencies>

        <dependency>
            <groupId>io.r2dbc</groupId>
            <artifactId>r2dbc-pool</artifactId>
            <version>1.0.1.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>r2dbc-postgresql</artifactId>
            <version>1.0.2.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>com.google.cloud.sql</groupId>
            <artifactId>cloud-sql-connector-r2dbc-postgres</artifactId>
            <version>1.15.0</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.9</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.9.3</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.9.3</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>17</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.2</version>
            </plugin>
        </plugins>
    </build>

</project>

Test class:

package com.test.cloudsql;

import static com.google.cloud.sql.core.GcpConnectionFactoryProvider.ENABLE_IAM_AUTH;
import static io.r2dbc.spi.ConnectionFactoryOptions.DATABASE;
import static io.r2dbc.spi.ConnectionFactoryOptions.DRIVER;
import static io.r2dbc.spi.ConnectionFactoryOptions.HOST;
import static io.r2dbc.spi.ConnectionFactoryOptions.PASSWORD;
import static io.r2dbc.spi.ConnectionFactoryOptions.PROTOCOL;
import static io.r2dbc.spi.ConnectionFactoryOptions.USER;

import io.r2dbc.pool.ConnectionPool;
import io.r2dbc.pool.ConnectionPoolConfiguration;
import io.r2dbc.spi.Connection;
import io.r2dbc.spi.ConnectionFactories;
import io.r2dbc.spi.ConnectionFactory;
import io.r2dbc.spi.ConnectionFactoryOptions;
import java.time.Instant;
import java.util.Timer;
import java.util.TimerTask;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import reactor.core.publisher.Mono;

public class CloudSqlFactoryTest {

    private static final Logger log = LoggerFactory.getLogger(CloudSqlFactoryTest.class);

    private ConnectionPool connectionPool;

    @BeforeEach
    public void setUpPool() {
        // Set up URL parameters
        ConnectionFactoryOptions options = ConnectionFactoryOptions.builder()
                .option(DRIVER, "pool")
                .option(PROTOCOL, "gcp:postgres")
                .option(PASSWORD, "ignored-but-required")
                .option(USER, "<IAM-USER>")
                .option(DATABASE, "<DB>>")
                .option(HOST, "<DB-HOST>>")
                .option(ENABLE_IAM_AUTH, true)
                .build();

        // Initialize connection pool
        ConnectionFactory connectionFactory = ConnectionFactories.get(options);

        ConnectionPoolConfiguration configuration = ConnectionPoolConfiguration
                .builder(connectionFactory)
                .build();

        this.connectionPool = new ConnectionPool(configuration);
    }

    @Test
    public void pooledConnectionTest() throws InterruptedException {
        final var connPool = this.connectionPool;
        TimerTask task = new TimerTask() {
            public void run() {
                log.info("Getting time from db");
                Mono.usingWhen(Mono.fromDirect(connPool.create()), (connection) -> Mono.fromDirect(
                                        connection.createStatement("SELECT NOW() as TS").execute())
                                .flatMapMany(
                                        (result) -> result.map((r, meta) -> r.get("TS", Instant.class)))
                                .next(), Connection::close, (o, throwable) -> o.close(), Connection::close)
                        .doOnNext(ts -> log.info("Got time from db: {}", ts))
                        .doOnError(ex -> log.error("Error getting time from db", ex))
                        .onErrorComplete()
                        .block();
            }
        };
        Timer timer = new Timer("Timer");
        timer.scheduleAtFixedRate(task, 0L, 5000L);

        Thread.sleep(1000L * 900); // sleep for 15 mins
        timer.cancel();
    }
}
```

### Stacktrace

```bash
io.r2dbc.postgresql.PostgresqlConnectionFactory$PostgresConnectionException: [08003] Cannot connect to 192.160.100.102/<unresolved>:3307

15:13:54   at io.r2dbc.postgresql.PostgresqlConnectionFactory.cannotConnect(PostgresqlConnectionFactory.java:188)

15:13:54   at io.r2dbc.postgresql.PostgresqlConnectionFactory.lambda$doCreateConnection$7(PostgresqlConnectionFactory.java:153)

15:13:54   at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3783)

15:13:54   at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)

15:13:54   at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)

15:13:54   at reactor.core.publisher.MonoDelayUntil$DelayUntilCoordinator.onError(MonoDelayUntil.java:200)

15:13:54   at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142)

15:13:54   at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:241)

15:13:54   at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:315)

15:13:54   at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)

15:13:54   at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:122)

15:13:54   at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:71)

15:13:54   at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)

15:13:54   at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)

15:13:54   at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)

15:13:54   at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)

15:13:54   at io.r2dbc.postgresql.client.AbstractPostgresSSLHandlerAdapter.completeHandshakeExceptionally(AbstractPostgresSSLHandlerAdapter.java:73)

15:13:54   at io.r2dbc.postgresql.client.AbstractPostgresSSLHandlerAdapter.operationComplete(AbstractPostgresSSLHandlerAdapter.java:55)

15:13:54   at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)

15:13:54   at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)

15:13:54   at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)

15:13:54   at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)

15:13:54   at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)

15:13:54   at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)

15:13:54   at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)

15:13:54   at io.netty.handler.ssl.SslHandler.handleUnwrapThrowable(SslHandler.java:1361)

15:13:54   at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1343)

15:13:54   at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387)

15:13:54   at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)

15:13:54   at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)

15:13:54   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)

15:13:54   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)

15:13:54   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

15:13:54   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

15:13:54   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)

15:13:54   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)

15:13:54   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

15:13:54   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)

15:13:54   at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)

15:13:54   at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)

15:13:54   at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)

15:13:54   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)

15:13:54   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

15:13:54   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

15:13:54   at java.base/java.lang.Thread.run(Thread.java:833)

15:13:54  Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

15:13:54   at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)

15:13:54   at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)

15:13:54   at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)

15:13:54   at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)

15:13:54   at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)

15:13:54   at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)

15:13:54   at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)

15:13:54   at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)

15:13:54   at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)

15:13:54   at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1277)

15:13:54   at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1264)

15:13:54   at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)

15:13:54   at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1209)

15:13:54   at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1651)

15:13:54   at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1497)

15:13:54   at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338)

15:13:54   ... 18 more

15:13:54  Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

15:13:54   at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)

15:13:54   at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)

15:13:54   at java.base/sun.security.validator.Validator.validate(Validator.java:264)

15:13:54   at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285)

15:13:54   at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)

15:13:54   at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)

15:13:54   ... 29 more

15:13:54  Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

15:13:54   at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)

15:13:54   at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)

15:13:54   at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)

15:13:54   at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)

15:13:54   ... 34 more
```

### Steps to reproduce?

1. Create a sample application with the provided pom.xml and a Junit test class
2. Run the test (which will connect to the database every 5 seconds for 15 mins)
3. Manually rotate the DB SSL certificate
4. Observe from error stack trace from the log
5. Rollback DB SSL certificate
6. Test is able to connect to the database 

### Environment

1. OS type and version: Ubuntu
2. Java SDK version: 17
3. Cloud SQL Java Socket Factory version: 1.15.0

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by ttosta-google**
Fixes #1719

### CODE REVIEW

**Comment by enocom** [comment]
To summarize a conversation elsewhere, we think this is the right solution and will test it in a Spring Boot app to double check it works as intended.

**Comment by enocom** [comment]
FWIW here's a v1 test where rotate the cert and verify the connection works: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/v1/tests/dialer_test.go#L36

**Comment by ttosta-google** [comment]
I've tested the fix in a Spring Boot app and it worked, i.e. app was able to connect to the DB after manually rotating the DB SSL certificate.

File: r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnection.java [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+    Publisher<Boolean> response = delegate.validate(depth);
+    Mono.from(response)
+        .doOnNext(
+            valid -> {
+              if (!valid) {
+                // Force refresh the connection info when it is invalid.
+                InternalConnectorRegistry.getInstance().forceRefresh(config);
+              }
+            })
+        .subscribeOn(Schedulers.boundedElastic())
```
Comment (enocom) [inline r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnection.java:133]: What is the significance of this line?

File: core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java [hunk 2]
```diff
@@ -191,6 +191,16 @@ public ConnectionMetadata getConnectionMetadata(ConnectionConfig config) {
     return getConnector(config).getConnection(config).getConnectionMetadata(connectTimeoutMs);
   }
 
+  /** Internal use only: Force refresh the connection info. */
+  public void forceRefresh(ConnectionConfig config) {
```
Comment (enocom) [inline core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java:195]: Shall we put some kind of unit test around this?

File: r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnection.java (hunk 1 above)
Comment (ttosta-google) [reply r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnection.java:133]: To prevent blocking returning. I've added a comment. Please let me know if it is still not clear.

File: core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java (hunk 2 above)
Comment (ttosta-google) [reply core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java:195]: Added.

File: r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnection.java (hunk 1 above)
Comment (enocom) [reply r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnection.java:134]: OK thanks. Minor nit: could we move the comment to directly above this line just to make that point clear?

**Review by enocom — APPROVED** [review]

File: r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnection.java (hunk 1 above)
Comment (ttosta-google) [reply r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnection.java:134]: Updated.

File: core/src/main/java/com/google/cloud/sql/core/ConnectionInfoRepositoryFactory.java [hunk 3]
```diff
@@ -22,6 +22,5 @@
 /** Factory interface for creating SQLAdmin clients to interact with Cloud SQL Admin API. */
 public interface ConnectionInfoRepositoryFactory {
```
[the remark this answers is not in the document]
Comment (ttosta-google) [reply core/src/main/java/com/google/cloud/sql/core/ConnectionInfoRepositoryFactory.java]: It should not. Updated.
